let shirt = [
    {src:"shirt/1.png",name:"Black Hood",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/2.png",name:"White Hood",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/3.png",name:"Grey Hood",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/4.png",name:"Grey Shirt",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/5.png",name:"Black Shirt",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/6.png",name:"White Shirt",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/7.png",name:"Blue Shirt",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
    {src:"shirt/8.png",name:"Red Shirt",by:"by Clover",detaile:"Short sleeve shirts for men are the best call for this summer season. This shirt style makes It a perfect piece of outfit for a walk around the streets or strolling through the park. You can use it with shorts or pair it up with a pair of denim. If it’s distressed jeans, better. Use sneakers, loafers, or typical canvas shoes with this shirt style and you’ll be in the best summer outfit.",price:"2500"},
]